# Generated by Django 4.1.1 on 2022-10-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('passwrd', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('tracking', models.BooleanField(default=True, verbose_name='회원상태')),
                ('insert_date', models.DateTimeField(verbose_name='insert date')),
                ('update_date', models.DateTimeField(verbose_name='update date')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['-insert_date'],
            },
        ),
    ]
