# Generated by Django 4.1.1 on 2022-10-04 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='타이틀')),
                ('description', models.TextField(verbose_name='설명')),
                ('game_html', models.CharField(max_length=100, verbose_name='게임html')),
                ('img_src', models.CharField(default='', max_length=100, verbose_name='이미지src')),
                ('is_show', models.BooleanField(default=True, verbose_name='show')),
                ('insert_date', models.DateTimeField(verbose_name='insert date')),
                ('update_date', models.DateTimeField(verbose_name='update date')),
            ],
            managers=[
                ('show', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(help_text='score id', primary_key=True, serialize=False)),
                ('score_data', models.CharField(max_length=100, verbose_name='점수정보')),
                ('insert_date', models.DateTimeField(verbose_name='insert date')),
                ('games_id', models.ForeignKey(db_column='games_id', on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.games')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['-insert_date'],
            },
        ),
    ]
